workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 30
    instance_type: linux_x2
    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Build Android Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/outputs/**/*.apk
      - app/build/outputs/**/*.apk
